-- Portable DDL for the Utility Configuration System data model.
-- Mirrors the original IBM i DB2 tables (UTCFG*). Use this for SQL Server / Postgres /
-- DB2 production deployments; the .NET API uses EF Core to create the SQLite dev DB.

CREATE TABLE UTCFGVTP (              -- Variable Type Definitions
    VTP_ID      INT PRIMARY KEY,
    VTP_NAME    VARCHAR(20)   NOT NULL,
    VTP_DESC    VARCHAR(50)   NOT NULL,
    VTP_PROC    VARCHAR(128)  NOT NULL,   -- validation procedure
    VTP_INFO    VARCHAR(2048) NOT NULL
);

CREATE TABLE UTCFGSRM (              -- Scope Resolution Methods
    SRM_ID      INT PRIMARY KEY,
    SRM_NAME    VARCHAR(20)   NOT NULL,
    SRM_DESC    VARCHAR(50)   NOT NULL,
    SRM_INFO    VARCHAR(2048) NOT NULL
);

CREATE TABLE UTCFGSRV (              -- Server Definitions
    SRV_ID      INT PRIMARY KEY,
    SRV_NAME    VARCHAR(20)   NOT NULL,
    SRV_DESC    VARCHAR(50)   NOT NULL,
    SRV_MATCH   VARCHAR(128)  NOT NULL,
    SRV_INFO    VARCHAR(2048) NOT NULL
);

CREATE TABLE UTCFGCTX (              -- Context Definitions
    CTX_ID      INT PRIMARY KEY,
    CTX_NAME    VARCHAR(20)   NOT NULL,
    CTX_DESC    VARCHAR(50)   NOT NULL,
    CTX_IS_SRV  DECIMAL(1,0)  NOT NULL,
    CTX_INFO    VARCHAR(2048) NOT NULL
);

CREATE TABLE UTCFGXTN (              -- Extent Definitions
    XTN_ID      INT PRIMARY KEY,
    CTX_ID      INT NOT NULL REFERENCES UTCFGCTX(CTX_ID),
    XTN_NAME    VARCHAR(20)   NOT NULL,
    XTN_DESC    VARCHAR(50)   NOT NULL,
    XTN_INFO    VARCHAR(2048) NOT NULL
);

CREATE TABLE UTCFGSCP (              -- Scope Definitions
    SCP_ID      INT PRIMARY KEY,
    SRV_ID      INT NOT NULL REFERENCES UTCFGSRV(SRV_ID),
    SRM_ID      INT NOT NULL REFERENCES UTCFGSRM(SRM_ID),
    SCP_NAME    VARCHAR(20)   NOT NULL,
    SCP_DESC    VARCHAR(50)   NOT NULL,
    SCP_IS_SRV  DECIMAL(1,0)  NOT NULL,
    SCP_MATCH   VARCHAR(128)  NOT NULL,
    SCP_INFO    VARCHAR(2048) NOT NULL
);

CREATE TABLE UTCFGVDF (              -- Variable Definitions
    VDF_ID      INT PRIMARY KEY,
    XTN_ID      INT NOT NULL REFERENCES UTCFGXTN(XTN_ID),
    VTP_ID      INT NOT NULL REFERENCES UTCFGVTP(VTP_ID),
    VDF_NAME    VARCHAR(50)   NOT NULL,
    VDF_DESC    VARCHAR(50)   NOT NULL,
    VDF_RSTRCT  DECIMAL(1,0)  NOT NULL,
    VDF_INFO    VARCHAR(2048) NOT NULL
);

CREATE TABLE UTCFGVVL (              -- Variable Valid Values
    VVL_ID      INT PRIMARY KEY,
    VDF_ID      INT NOT NULL REFERENCES UTCFGVDF(VDF_ID),
    VVL_VALUE   VARCHAR(128)  NOT NULL,
    VVL_DESC    VARCHAR(50)   NOT NULL,
    VVL_INFO    VARCHAR(2048) NOT NULL
);

CREATE TABLE UTCFGVAL (              -- Variable Values (per scope)
    VAL_ID      INT PRIMARY KEY,
    VDF_ID      INT NOT NULL REFERENCES UTCFGVDF(VDF_ID),
    SCP_ID      INT NOT NULL REFERENCES UTCFGSCP(SCP_ID),
    VAL_VARVAL  VARCHAR(128)  NOT NULL
);
